/** MAIN AGORA CHAT SERVER : THIS'LL PROVIDE THE SMOOTH PLACE TO CHAT, THIS WILL BE THE MAIN PLACE FROM WHERE THE USER CREATE IT'S OWN CHAT APPLICATION. HERE AS (agora server) WILL ONLY TAKE HOSTID AND PROVIDE THE SERVICE
 */

